#!/usr/bin/env ruby

$LOAD_PATH.unshift File.dirname( __FILE__ )
require "config"
require "rake"

sh "/sbin/ifconfig #{ ARGV[ 0 ] } 0.0.0.0 down"
sh "#{ $ovs_vsctl } del-port #{ $bridge[ $tap.invert[ ARGV[ 0 ] ] ] } #{ ARGV[ 0 ] }"
