#!/usr/bin/env ruby

$LOAD_PATH.unshift File.dirname( __FILE__ )
require "config"
require "rake"

sh "/sbin/ifconfig #{ ARGV[ 0 ] } 0.0.0.0 down"
$vm.each do | name, attr |
  if attr[ :tap ] == ARGV[ 0 ]
    sh "#{ vsctl } del-port #{ $switch[ name ][ :bridge ] } #{ ARGV[ 0 ] }"
    exit
  end
end
